server:
  port: 8091

spring:
  profiles:
    active: dev
  application:
    name: eden-product
  datasource:
    name: eden
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.12.79.78:3306/eden
      username: root
      password: Asd09876%
  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
  redis:
    database: 0
    host: 106.12.79.78
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
  rabbitmq:
    host: 106.12.79.78
    port: 5672
    username: root
    password: Asd09876%
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true

dubbo:
  application:
    name: product-service
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://106.12.79.78:2181 #nacos://106.14.187.183:8848
  provider:
    timeout: 60000
    retries: 3
    loadbalance: roundrobin

